# EDA + ETL

Load all parquet files from `processed/`, then inspect `sequences.parquet`.

In [14]:
%reset -f
from pathlib import Path

import pandas as pd

In [15]:
processed_dir = Path("processed")
parquet_files = sorted(processed_dir.glob("*.parquet"))

if not parquet_files:
    raise FileNotFoundError(f"No parquet files found in {processed_dir.resolve()}")

all_parquets = {file.stem: pd.read_parquet(file) for file in parquet_files}

print(f"Loaded {len(all_parquets)} parquet files:")
for name, df in all_parquets.items():
    print(f"- {name}: {df.shape}")

Loaded 8 parquet files:
- app_category_mapping: (48, 3)
- app_metadata: (10173, 9)
- enriched_mobilerec_interactions: (19297019, 7)
- enriched_mobilerec_sequences: (700111, 14)
- interactions: (19297019, 9)
- item_mapping: (10173, 2)
- sequences: (700111, 11)
- user_mapping: (700111, 2)

In [16]:
sequences_df = pd.read_parquet(processed_dir / "sequences.parquet")
sequences_df

,user_id,sequence_length,train_sequence,validation_sequence,test_sequence,validation_target,test_target,timestamps,app_packages,ratings,votes
0,1,84,"[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...",5661,3207,"[1378699200, 1400299200, 1449810000, 145663560...","[com.inxile.BardTale, com.move.rentals, com.to...","[1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 4.0, 2.0, 4.0, ...","[0, 0, 5, 0, 0, 0, 0, 27, 0, 4, 1, 0, 1, 0, 29..."
1,2,9,"[3320, 9767, 1189, 8021, 3416, 212, 1764]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316...",2316,6499,"[1546923600, 1556251200, 1565150400, 158623200...","[com.g5e.survivors, org.mozilla.focus, com.asi...","[1.0, 3.0, 5.0, 5.0, 1.0, 5.0, 5.0, 4.0, 5.0]","[0, 7, 14, 0, 0, 0, 64, 0, 0]"
2,3,25,"[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...",6807,9474,"[1442635200, 1530244800, 1530417600, 154407240...","[com.tripomatic, com.yammer.v1, com.dsemu.dras...","[5.0, 4.0, 3.0, 2.0, 5.0, 3.0, 2.0, 5.0, 1.0, ...","[0, 0, 1, 6, 0, 2, 30, 0, 1, 0, 0, 2, 2, 2, 0,..."
3,4,6,"[8742, 5756, 5560, 1673]","[8742, 5756, 5560, 1673, 5025]","[8742, 5756, 5560, 1673, 5025, 2413]",5025,2413,"[1554955200, 1585195200, 1618804800, 162329760...","[com.yboga.dreamhospital, com.ninegag.android....","[5.0, 5.0, 2.0, 5.0, 5.0, 4.0]","[0, 0, 88, 0, 0, 0]"
4,5,35,"[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...",3850,6234,"[1381118400, 1435118400, 1460520000, 146077920...","[com.mtvn.tmntrooftoprun, org.withouthat.acale...","[1.0, 2.0, 3.0, 1.0, 1.0, 3.0, 5.0, 4.0, 3.0, ...","[0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 118, 2, 1, 0, 1..."
...,...,...,...,...,...,...,...,...,...,...,...
700106,700107,6,"[3347, 4545, 3532, 3822]","[3347, 4545, 3532, 3822, 6760]","[3347, 4545, 3532, 3822, 6760, 10171]",6760,10171,"[1535428800, 1589342400, 1589774400, 163556640...","[com.gamebeartech.nova, com.juphoon.justalk, c...","[2.0, 1.0, 5.0, 4.0, 4.0, 5.0]","[0, 3, 2, 0, 0, 0]"
700107,700108,5,"[3227, 3783, 1575]","[3227, 3783, 1575, 9960]","[3227, 3783, 1575, 9960, 5130]",9960,5130,"[1484456400, 1563076800, 1595995200, 163911240...","[com.fstop.photo, com.greysprings.kindergarten...","[4.0, 3.0, 4.0, 2.0, 1.0]","[0, 0, 9, 0, 3]"
700108,700109,9,"[9271, 6408, 8369, 7402, 6358, 8229, 7977]","[9271, 6408, 8369, 7402, 6358, 8229, 7977, 10155]","[9271, 6408, 8369, 7402, 6358, 8229, 7977, 101...",10155,2763,"[1592193600, 1600833600, 1615266000, 161897760...","[islamicsongs.nasheed.nashydlagu, com.pnixgame...","[5.0, 2.0, 3.0, 4.0, 5.0, 5.0, 2.0, 1.0, 5.0]","[0, 0, 0, 0, 5, 0, 1, 10, 0]"
700109,700110,9,"[6641, 2046, 4396, 7012, 7698, 5776, 5286]","[6641, 2046, 4396, 7012, 7698, 5776, 5286, 2660]","[6641, 2046, 4396, 7012, 7698, 5776, 5286, 266...",2660,366,"[1434686400, 1503028800, 1553054400, 156160800...","[com.rayark.pluto, com.coffeestainstudios.goat...","[2.0, 3.0, 5.0, 5.0, 1.0, 3.0, 5.0, 4.0, 5.0]","[0, 0, 4, 9, 1, 1, 0, 0, 0]"
700110,700111,5,"[8071, 3943, 5520]","[8071, 3943, 5520, 9976]","[8071, 3943, 5520, 9976, 8044]",9976,8044,"[1530244800, 1540958400, 1584676800, 160247520...","[com.tricksterarts.hackers, com.hellofresh.and...","[3.0, 3.0, 2.0, 3.0, 1.0]","[8, 0, 0, 0, 40]"

In [17]:
print("Columns:")
print(sequences_df.columns.tolist())

Columns:
['user_id', 'sequence_length', 'train_sequence', 'validation_sequence', 'test_sequence', 'validation_target', 'test_target', 'timestamps', 'app_packages', 'ratings', 'votes']

In [18]:
print("Head:")
sequences_df.head()

Head:

,user_id,sequence_length,train_sequence,validation_sequence,test_sequence,validation_target,test_target,timestamps,app_packages,ratings,votes
0,1,84,"[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...",5661,3207,"[1378699200, 1400299200, 1449810000, 145663560...","[com.inxile.BardTale, com.move.rentals, com.to...","[1.0, 2.0, 3.0, 4.0, 5.0, 1.0, 4.0, 2.0, 4.0, ...","[0, 0, 5, 0, 0, 0, 0, 27, 0, 4, 1, 0, 1, 0, 29..."
1,2,9,"[3320, 9767, 1189, 8021, 3416, 212, 1764]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316...",2316,6499,"[1546923600, 1556251200, 1565150400, 158623200...","[com.g5e.survivors, org.mozilla.focus, com.asi...","[1.0, 3.0, 5.0, 5.0, 1.0, 5.0, 5.0, 4.0, 5.0]","[0, 7, 14, 0, 0, 0, 64, 0, 0]"
2,3,25,"[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...",6807,9474,"[1442635200, 1530244800, 1530417600, 154407240...","[com.tripomatic, com.yammer.v1, com.dsemu.dras...","[5.0, 4.0, 3.0, 2.0, 5.0, 3.0, 2.0, 5.0, 1.0, ...","[0, 0, 1, 6, 0, 2, 30, 0, 1, 0, 0, 2, 2, 2, 0,..."
3,4,6,"[8742, 5756, 5560, 1673]","[8742, 5756, 5560, 1673, 5025]","[8742, 5756, 5560, 1673, 5025, 2413]",5025,2413,"[1554955200, 1585195200, 1618804800, 162329760...","[com.yboga.dreamhospital, com.ninegag.android....","[5.0, 5.0, 2.0, 5.0, 5.0, 4.0]","[0, 0, 88, 0, 0, 0]"
4,5,35,"[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...",3850,6234,"[1381118400, 1435118400, 1460520000, 146077920...","[com.mtvn.tmntrooftoprun, org.withouthat.acale...","[1.0, 2.0, 3.0, 1.0, 1.0, 3.0, 5.0, 4.0, 3.0, ...","[0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 118, 2, 1, 0, 1..."

In [19]:
print("Tail:")
sequences_df.tail()

Tail:

,user_id,sequence_length,train_sequence,validation_sequence,test_sequence,validation_target,test_target,timestamps,app_packages,ratings,votes
700106,700107,6,"[3347, 4545, 3532, 3822]","[3347, 4545, 3532, 3822, 6760]","[3347, 4545, 3532, 3822, 6760, 10171]",6760,10171,"[1535428800, 1589342400, 1589774400, 163556640...","[com.gamebeartech.nova, com.juphoon.justalk, c...","[2.0, 1.0, 5.0, 4.0, 4.0, 5.0]","[0, 3, 2, 0, 0, 0]"
700107,700108,5,"[3227, 3783, 1575]","[3227, 3783, 1575, 9960]","[3227, 3783, 1575, 9960, 5130]",9960,5130,"[1484456400, 1563076800, 1595995200, 163911240...","[com.fstop.photo, com.greysprings.kindergarten...","[4.0, 3.0, 4.0, 2.0, 1.0]","[0, 0, 9, 0, 3]"
700108,700109,9,"[9271, 6408, 8369, 7402, 6358, 8229, 7977]","[9271, 6408, 8369, 7402, 6358, 8229, 7977, 10155]","[9271, 6408, 8369, 7402, 6358, 8229, 7977, 101...",10155,2763,"[1592193600, 1600833600, 1615266000, 161897760...","[islamicsongs.nasheed.nashydlagu, com.pnixgame...","[5.0, 2.0, 3.0, 4.0, 5.0, 5.0, 2.0, 1.0, 5.0]","[0, 0, 0, 0, 5, 0, 1, 10, 0]"
700109,700110,9,"[6641, 2046, 4396, 7012, 7698, 5776, 5286]","[6641, 2046, 4396, 7012, 7698, 5776, 5286, 2660]","[6641, 2046, 4396, 7012, 7698, 5776, 5286, 266...",2660,366,"[1434686400, 1503028800, 1553054400, 156160800...","[com.rayark.pluto, com.coffeestainstudios.goat...","[2.0, 3.0, 5.0, 5.0, 1.0, 3.0, 5.0, 4.0, 5.0]","[0, 0, 4, 9, 1, 1, 0, 0, 0]"
700110,700111,5,"[8071, 3943, 5520]","[8071, 3943, 5520, 9976]","[8071, 3943, 5520, 9976, 8044]",9976,8044,"[1530244800, 1540958400, 1584676800, 160247520...","[com.tricksterarts.hackers, com.hellofresh.and...","[3.0, 3.0, 2.0, 3.0, 1.0]","[8, 0, 0, 0, 40]"

In [20]:
user_mapping_df = pd.read_parquet(processed_dir / "user_mapping.parquet")
user_mapping_df

                     uid  user_id
0       000O5329PtxPH4SB        1
1       000clAT5Tras2VRb        2
2       0017GZyW7Tf8nVrl        3
3       001AR1RmuEaEva5F        4
4       001BQE4AdpoCgOC8        5
...                  ...      ...
700106  zzz4WeO8SJWnosqj   700107
700107  zzzAXXhMywnWtGac   700108
700108  zzzHJoqySDHimsYR   700109
700109  zzzd5wPxHxJp649F   700110
700110  zzznxhRT6cXmZ33S   700111

[700111 rows x 2 columns]

In [21]:
interactions_df = pd.read_parquet(processed_dir / "interactions.parquet")
interactions_df

,user_id,item_id,uid,app_package,app_category,rating,votes,timestamp,position
0,1,4380,000O5329PtxPH4SB,com.inxile.BardTale,Role Playing,1.0,0,1378699200,1
1,1,5456,000O5329PtxPH4SB,com.move.rentals,House & Home,2.0,0,1400299200,2
2,1,7967,000O5329PtxPH4SB,com.tocaboca.tocacity,Education,3.0,5,1449810000,3
3,1,2300,000O5329PtxPH4SB,com.daysofwonder.tt.android,Board,4.0,0,1456635600,4
4,1,1250,000O5329PtxPH4SB,com.atlasappco.fanduellineups,Sports,5.0,0,1461902400,5
...,...,...,...,...,...,...,...,...,...
19297014,700111,8071,zzznxhRT6cXmZ33S,com.tricksterarts.hackers,Strategy,3.0,8,1530244800,1
19297015,700111,3943,zzznxhRT6cXmZ33S,com.hellofresh.androidapp,Food & Drink,3.0,0,1540958400,2
19297016,700111,5520,zzznxhRT6cXmZ33S,com.my.warface.online.fps.pvp.action.shooter,Action,2.0,0,1584676800,3
19297017,700111,9976,zzznxhRT6cXmZ33S,seesaw.shadowpuppet.co.classroom,Education,3.0,0,1602475200,4
19297018,700111,8044,zzznxhRT6cXmZ33S,com.transferwise.android,Finance,1.0,40,1647921600,5

In [22]:
app_metadata_df = pd.read_parquet(processed_dir / "app_metadata.parquet")
app_category_counts = (
    app_metadata_df["app_category"]
    .fillna("<missing>")
    .value_counts(dropna=False)
    .rename_axis("app_category")
    .reset_index(name="count")
    .sort_values(["count", "app_category"], ascending=[False, True], kind="stable")
    .reset_index(drop=True)
)
print(f"Unique categories: {app_metadata_df['app_category'].nunique(dropna=True)}")
app_category_mapping_df = app_category_counts.copy()
app_category_mapping_df.insert(0, "app_category_id", range(1, len(app_category_mapping_df) + 1))
app_category_mapping_path = processed_dir / "app_category_mapping.parquet"
app_category_mapping_df.to_parquet(app_category_mapping_path, index=False)
print(f"Saved category mapping to {app_category_mapping_path}")
app_category_mapping_df

Unique categories: 48
Saved category mapping to processed/app_category_mapping.parquet

    app_category_id             app_category  count
0                 1             Role Playing    658
1                 2                   Puzzle    537
2                 3               Simulation    537
3                 4                   Action    529
4                 5                 Strategy    520
5                 6                   Casual    432
6                 7                Education    429
7                 8                  Medical    422
8                 9              Educational    420
9                10                Adventure    397
10               11                   Sports    289
11               12                   Arcade    264
12               13             Productivity    260
13               14                  Finance    254
14               15                   Dating    234
15               16           Travel & Local    228
16               17                 Shopping    223
17               18            Entertainment    216
18               19                    Tools    214
19               20                   Casino    199
20               21                     Card    187
21               22         Libraries & Demo    176
22               23            Music & Audio    175
23               24                    Board    154
24               25                 Business    153
25               26             Food & Drink    151
26               27                     Word    149
27               28         Health & Fitness    148
28               29                Lifestyle    143
29               30                   Racing    141
30               31            Communication    125
31               32          Personalization    120
32               33                   Social    119
33               34              Photography    114
34               35        Books & Reference    107
35               36  Video Players & Editors     94
36               37        Maps & Navigation     92
37               38                    Music     86
38               39             House & Home     77
39               40                Parenting     71
40               41         News & Magazines     69
41               42             Art & Design     54
42               43                  Weather     51
43               44          Auto & Vehicles     46
44               45                   Comics     38
45               46                   Trivia     32
46               47                   Beauty     21
47               48                   Events     18

In [23]:
app_metadata_df = pd.read_parquet(processed_dir / "app_metadata.parquet")
display(app_metadata_df)

,app_package,app_name,developer_name,app_category,description,content_rating,num_reviews,price,avg_rating
0,com.natewren.lines,Lines Pro - Icon Pack,Nate Wren Design,Personalization,Lines icons (pro version) are outlined shapes ...,Everyone,"2,997",$1.99 Buy,4.7
1,com.capitalone.credittracker,CreditWise from Capital One,"Capital One Services, LLC",Finance,Know your credit score and much more\n\nCapita...,Everyone,"94,914",Install,4.7
2,com.purascents.android,Pura - Smart Fragrance Dispenser,Pura,House & Home,Pura is a smart home fragrance device that you...,Everyone,778,Install,4.4
3,com.wallethub.mywallet,"WalletHub - Free Credit Score, Report & Monito...",WalletHub,Finance,WalletHub is the first app to offer 100% free ...,Everyone,"7,025",Install,4.7
4,air.com.samuramu.gg.se,#SelfLove (GG Confidence & Self esteem),Ggtude Ltd,Medical,Wish to build confidence and have higher self ...,Everyone,625,Install,4.1
...,...,...,...,...,...,...,...,...,...
10168,com.unysyegor.effects.neon.magicslate,Magic Slate - Neon Effects,Unysyegor,Entertainment,Magic Slate Neon Effects app contains on learn...,Everyone,0,Install,0.0
10169,com.romancestories.novel,Romance Stories-eBooks &Novels,Romance Stories Studio,Books & Reference,Romance Stories - Romantic Story & Fantasy Nov...,Teen,"2,591",Install,4.9
10170,com.cornerdesk.gfx.nstate,PUBG NEW STATE : GFX Tool Pro + 90FPS,CornerDesk Inc.,Libraries & Demo,GFX Tool is a free utility launcher for FPS ga...,Everyone,226,$2.49 Buy,1.0
10171,com.picture.magic.imager,Magic Photo Editor:Foto Repair,Zachary Holt,Photography,"Hi friends, the first photo editor to meet you...",Everyone,"2,724",Install,4.4
10172,cyberwolf.musicplayer,Music Player - MP3 & Audio,Elysium Group,Music & Audio,TREBL is a music player focused on providing t...,Everyone,"21,743",Install,4.6

In [24]:
# Smoke test: set SEQUENCE_SAMPLE_N to a small number like 1000.
# Full execution: set SEQUENCE_SAMPLE_N = None.
# Use "head" for a fast deterministic check, or "sample" for a random slice.
SEQUENCE_SAMPLE_N = None
SEQUENCE_SAMPLE_MODE = "head"

sequences_df = pd.read_parquet(processed_dir / "sequences.parquet")
if SEQUENCE_SAMPLE_N is not None:
    if SEQUENCE_SAMPLE_MODE == "sample":
        sequences_df = sequences_df.sample(
            n=min(SEQUENCE_SAMPLE_N, len(sequences_df)),
            random_state=42,
        ).reset_index(drop=True)
    else:
        sequences_df = sequences_df.head(SEQUENCE_SAMPLE_N).copy()
print(f"Running enrichment on {len(sequences_df):,} sequence rows")

item_mapping_df = pd.read_parquet(processed_dir / "item_mapping.parquet")
app_metadata_df = pd.read_parquet(processed_dir / "app_metadata.parquet")
app_category_mapping_df = pd.read_parquet(processed_dir / "app_category_mapping.parquet")

item_features_df = (
    item_mapping_df
    .merge(
        app_metadata_df[["app_package", "app_category", "num_reviews", "avg_rating", "price"]],
        on="app_package",
        how="left",
    )
    .merge(
        app_category_mapping_df[["app_category_id", "app_category"]],
        on="app_category",
        how="left",
    )
)

item_features_df["app_category_id"] = item_features_df["app_category_id"].fillna(0).astype(int)
item_features_df["num_reviews_numeric"] = pd.to_numeric(
    item_features_df["num_reviews"].astype("string").str.replace(",", "", regex=False),
    errors="coerce",
).fillna(0).astype(int)
item_features_df["avg_rating_scaled"] = (
    ((item_features_df["avg_rating"].fillna(0) - 1.0) / 4.0)
    .clip(lower=0.0, upper=1.0)
    .round(4)
)
item_features_df["price_numeric"] = pd.to_numeric(
    item_features_df["price"].astype("string").str.extract(r"\$\s*([0-9]+(?:\.[0-9]+)?)", expand=False),
    errors="coerce",
).fillna(0.0).round(2)

category_lookup = item_features_df.set_index("item_id")["app_category_id"].to_dict()
num_reviews_lookup = item_features_df.set_index("item_id")["num_reviews_numeric"].to_dict()
avg_rating_lookup = item_features_df.set_index("item_id")["avg_rating_scaled"].to_dict()
price_lookup = item_features_df.set_index("item_id")["price_numeric"].to_dict()

sequences_enriched_df = (
    sequences_df.drop(columns=["app_packages"])
    .rename(columns={"votes": "review_upvotes"})
    .copy()
)
# Preserve the original per-user, per-item vote counts under an explicit feature name.
sequences_enriched_df["review_upvotes"] = sequences_enriched_df["review_upvotes"].apply(
    lambda seq: [int(vote) for vote in seq]
)
# Binarize the original 1-5 ratings into implicit feedback labels.
sequences_enriched_df["ratings"] = sequences_enriched_df["ratings"].apply(
    lambda seq: [1 if float(rating) >= 3 else -1 for rating in seq]
)
sequences_enriched_df["app_category"] = sequences_enriched_df["test_sequence"].apply(
    lambda seq: [[int(category_lookup.get(item_id, 0))] for item_id in seq]
)
sequences_enriched_df["app_num_reviews"] = sequences_enriched_df["test_sequence"].apply(
    lambda seq: [int(num_reviews_lookup.get(item_id, 0)) for item_id in seq]
)
sequences_enriched_df["app_avg_rating"] = sequences_enriched_df["test_sequence"].apply(
    lambda seq: [float(avg_rating_lookup.get(item_id, 0.0)) for item_id in seq]
)
sequences_enriched_df["app_price"] = sequences_enriched_df["test_sequence"].apply(
    lambda seq: [float(price_lookup.get(item_id, 0.0)) for item_id in seq]
)

sequences_enriched_df.head()

Running enrichment on 700,111 sequence rows

,user_id,sequence_length,train_sequence,validation_sequence,test_sequence,validation_target,test_target,timestamps,ratings,review_upvotes,app_category,app_num_reviews,app_avg_rating,app_price
0,1,84,"[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...","[4380, 5456, 7967, 2300, 1250, 5562, 3622, 896...",5661,3207,"[1378699200, 1400299200, 1449810000, 145663560...","[-1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1...","[0, 0, 5, 0, 0, 0, 0, 27, 0, 4, 1, 0, 1, 0, 29...","[[1], [39], [7], [24], [11], [13], [4], [19], ...","[71708, 10619, 32525, 18718, 1755, 100153, 685...","[0.9, 0.75, 0.8, 0.925, 0.875, 0.9, 0.85, 0.82...","[2.99, 0.0, 3.99, 6.99, 0.0, 0.0, 0.0, 0.0, 0...."
1,2,9,"[3320, 9767, 1189, 8021, 3416, 212, 1764]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316]","[3320, 9767, 1189, 8021, 3416, 212, 1764, 2316...",2316,6499,"[1546923600, 1556251200, 1565150400, 158623200...","[-1, 1, 1, 1, -1, 1, 1, 1, 1]","[0, 7, 14, 0, 0, 0, 64, 0, 0]","[[10], [31], [33], [5], [4], [2], [10], [1], [...","[398072, 72641, 192160, 29372, 542501, 1571, 1...","[0.8, 0.875, 0.8, 0.9, 0.825, 0.75, 0.925, 0.9...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
2,3,25,"[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...","[8086, 8734, 2608, 361, 8129, 6483, 8213, 4354...",6807,9474,"[1442635200, 1530244800, 1530417600, 154407240...","[1, 1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, ...","[0, 0, 1, 6, 0, 2, 30, 0, 1, 0, 0, 2, 2, 2, 0,...","[[16], [25], [4], [33], [24], [9], [31], [2], ...","[15962, 66905, 117456, 268324, 271433, 49874, ...","[0.825, 0.9, 0.85, 0.725, 0.875, 0.8, 0.775, 0...","[0.0, 0.0, 4.99, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
3,4,6,"[8742, 5756, 5560, 1673]","[8742, 5756, 5560, 1673, 5025]","[8742, 5756, 5560, 1673, 5025, 2413]",5025,2413,"[1554955200, 1585195200, 1618804800, 162329760...","[1, 1, -1, 1, 1, 1]","[0, 0, 88, 0, 0, 0]","[[3], [18], [2], [14], [29], [14]]","[67609, 1699589, 133684, 25222, 8480, 233418]","[0.8, 0.85, 0.8, 0.825, 0.625, 0.925]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
4,5,35,"[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...","[5481, 9838, 3375, 7533, 243, 7831, 5358, 5516...",3850,6234,"[1381118400, 1435118400, 1460520000, 146077920...","[-1, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1...","[0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 118, 2, 1, 0, 1...","[[4], [13], [3], [32], [1], [24], [2], [12], [...","[7614, 32949, 244987, 11225, 1446, 109633, 176...","[0.75, 0.9, 0.875, 0.775, 0.8, 0.85, 0.85, 0.8...","[3.99, 5.99, 0.0, 1.99, 3.99, 0.0, 0.0, 0.0, 0..."

In [25]:
interactions_df = pd.read_parquet(processed_dir / "interactions.parquet")
app_category_mapping_df = pd.read_parquet(processed_dir / "app_category_mapping.parquet")

interaction_category_lookup = app_category_mapping_df.set_index("app_category")["app_category_id"].to_dict()
interactions_enriched_df = (
    interactions_df.drop(columns=["app_package", "uid", "app_category"])
    .rename(columns={"votes": "review_upvotes"})
    .copy()
)
interactions_enriched_df["review_upvotes"] = interactions_enriched_df["review_upvotes"].fillna(0).astype(int)
interactions_enriched_df["rating"] = interactions_enriched_df["rating"].apply(
    lambda rating: 1 if float(rating) >= 3 else -1
)
interactions_enriched_df["app_category"] = (
    interactions_df["app_category"]
    .map(interaction_category_lookup)
    .fillna(0)
    .astype(int)
    .apply(lambda x: [x])
)

enriched_interactions_path = processed_dir / "enriched_mobilerec_interactions.parquet"
interactions_enriched_df.to_parquet(enriched_interactions_path, index=False)
print(f"Saved enriched interactions to {enriched_interactions_path}")
interactions_enriched_df

Saved enriched interactions to processed/enriched_mobilerec_interactions.parquet

,user_id,item_id,rating,review_upvotes,timestamp,position,app_category
0,1,4380,-1,0,1378699200,1,[1]
1,1,5456,-1,0,1400299200,2,[39]
2,1,7967,1,5,1449810000,3,[7]
3,1,2300,1,0,1456635600,4,[24]
4,1,1250,1,0,1461902400,5,[11]
...,...,...,...,...,...,...,...
19297014,700111,8071,1,8,1530244800,1,[5]
19297015,700111,3943,1,0,1540958400,2,[26]
19297016,700111,5520,-1,0,1584676800,3,[4]
19297017,700111,9976,1,0,1602475200,4,[7]
19297018,700111,8044,-1,40,1647921600,5,[14]

In [26]:
# Smoke test: keep UPLOAD_TO_KAGGLE = False.
# Full publish: set UPLOAD_TO_KAGGLE = True and keep SEQUENCE_SAMPLE_N = None in the previous cell.
UPLOAD_TO_KAGGLE = SEQUENCE_SAMPLE_N is None

from models.upload_processed_to_kaggle import (
    collect_dataset_files,
    load_kaggle_credentials,
    upload_kaggle_dataset_snapshot,
)

enriched_sequences_path = processed_dir / "enriched_mobilerec_sequences.parquet"
enriched_interactions_path = processed_dir / "enriched_mobilerec_interactions.parquet"
sequences_enriched_df.to_parquet(enriched_sequences_path, index=False)
print(f"Saved enriched sequences to {enriched_sequences_path}")
if not enriched_interactions_path.exists():
    raise FileNotFoundError(
        f"Run the interactions enrichment cell first: {enriched_interactions_path}"
    )

if UPLOAD_TO_KAGGLE:
    env_path, kaggle_username, _ = load_kaggle_credentials(Path(".env"))
    kaggle_dataset_handle = f"{kaggle_username}/cs5242-mobilerec-dataset"
    dataset_files = collect_dataset_files(processed_dir)
    dataset_files.pop("enriched_mobilerec_sequences.parquet", None)
    dataset_files.pop("enriched_mobilerec_interactions.parquet", None)
    dataset_files["enriched_mobilerec_sequences.parquet"] = enriched_sequences_path.resolve()
    dataset_files["enriched_mobilerec_interactions.parquet"] = enriched_interactions_path.resolve()
    upload_kaggle_dataset_snapshot(
        kaggle_dataset_handle,
        dataset_files,
        version_notes="refresh mobilerec dataset with enriched mobilerec sequences and interactions parquet",
    )
else:
    print("Skipped Kaggle upload. Set UPLOAD_TO_KAGGLE = True for the full publish run.")

Saved enriched sequences to processed/enriched_mobilerec_sequences.parquet
Uploading Dataset https://api.kaggle.com/datasets/gitaalekhyapaul/cs5242-mobilerec-dataset ...
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/summary.json

Uploading: 100%|██████████| 186/186 [00:00<00:00, 210B/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/summary.json (186B)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/interactions.parquet

Uploading: 100%|██████████| 199M/199M [00:13<00:00, 14.6MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/interactions.parquet (190MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/app_category_mapping.parquet

Uploading: 100%|██████████| 3.43k/3.43k [00:00<00:00, 4.22kB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/app_category_mapping.parquet (3KB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/user_mapping.parquet

Uploading: 100%|██████████| 14.5M/14.5M [00:03<00:00, 4.76MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/user_mapping.parquet (14MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/enriched_mobilerec_sequences.parquet

Uploading: 100%|██████████| 229M/229M [00:14<00:00, 15.7MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/enriched_mobilerec_sequences.parquet (218MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/enriched_mobilerec_interactions.parquet

Uploading: 100%|██████████| 109M/109M [00:08<00:00, 12.9MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/enriched_mobilerec_interactions.parquet (104MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/sequences.parquet

Uploading: 100%|██████████| 198M/198M [00:12<00:00, 15.3MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/sequences.parquet (189MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/app_metadata.parquet

Uploading: 100%|██████████| 13.1M/13.1M [00:02<00:00, 4.54MB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/app_metadata.parquet (12MB)
Starting upload for file /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/item_mapping.parquet

Uploading: 100%|██████████| 208k/208k [00:01<00:00, 140kB/s]

Upload successful: /var/folders/fg/p6f6x7z11qb2jtk9d1gdsdlw0000gn/T/kagglehub_dataset_kbk5r29g/item_mapping.parquet (203KB)

Your dataset version has been created.
Files are being processed...
See at: https://api.kaggle.com/datasets/gitaalekhyapaul/cs5242-mobilerec-dataset
Uploaded 9 file(s) to https://www.kaggle.com/datasets/gitaalekhyapaul/cs5242-mobilerec-dataset
- app_category_mapping.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/app_category_mapping.parquet
- app_metadata.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/app_metadata.parquet
- enriched_mobilerec_interactions.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/enriched_mobilerec_interactions.parquet
- enriched_mobilerec_sequences.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/enriched_mobilerec_sequences.parquet
- interactions.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/interactions.parquet
- item_mapping.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/item_mapping.parquet
- sequences.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/sequences.parquet
- summary.json: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/summary.json
- user_mapping.parquet: /Users/gitaalekhyapaul/Documents/[Local] CS5242/cs5242-project/processed/user_mapping.parquet